ARG BASE_IMAGE=NONE
FROM ${BASE_IMAGE}

# disable terminal interaction for apt
ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=/bin/bash
SHELL ["/bin/bash", "-c"]

# add kitware's gpg key
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
    gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null

# add yarn's gpg key
RUN wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg 2>/dev/null | \
    gpg --dearmor - | tee /usr/share/keyrings/yarn-archive-keyring.gpg >/dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian stable main" \
      > /etc/apt/sources.list.d/yarn.list

# store apt-get packages in the docker cache so they won't need to be re-downloaded
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    apt-get update

# clean stale apt metadata and remove old repo entries
RUN rm -rf /var/lib/apt/lists/* && \
    sed -i '/isaac-ros\/release-3/d' /etc/apt/sources.list

# install isaac ros repo key using modern method
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y wget gnupg && \
    wget -qO - https://isaac.download.nvidia.com/isaac-ros/repos.key \
        | gpg --dearmor -o /usr/share/keyrings/isaac-ros.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/isaac-ros.gpg] \
        https://isaac.download.nvidia.com/isaac-ros/release-3 \
        $(. /etc/os-release && echo $VERSION_CODENAME) release-3.0" \
        > /etc/apt/sources.list.d/isaac-ros.list && \
    apt-get update

    # install python dependencies
RUN pip3 install --no-input --no-cache-dir -U \
    numba==0.58.1 \
    transformations==2022.9.26 \
    icecream==2.1.3 \
    jetson-stats \
    pyudev \
    filterpy \
    lap \
    scipy

# install apt dependencies
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
    evtest \
    gdb \
    gpiod \
    joystick \
    libgpiod-dev \
    libtool-bin \
    python3-posix-ipc \
    stm32flash \
    python3-pytest

# install missing ros packages
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
    ros-humble-can-msgs \
    ros-humble-geographic-msgs \
    ros-humble-isaac-ros-argus-camera \
    ros-humble-isaac-ros-h264-decoder \
    ros-humble-isaac-ros-h264-encoder \
    ros-humble-isaac-ros-image-pipeline \
    ros-humble-isaac-ros-jetson-stats \
    ros-humble-isaac-ros-managed-nitros \
    ros-humble-isaac-ros-nitros \
    ros-humble-isaac-ros-nitros-image-type \
    ros-humble-isaac-ros-yolov8 \
    ros-humble-joint-state-publisher \
    ros-humble-joint-state-publisher-gui \
    ros-humble-magic-enum \
    ros-humble-nmea-msgs \
    ros-humble-point-cloud-transport \
    ros-humble-point-cloud-transport-plugins \
    ros-humble-robot-localization \
    ros-humble-robot-localization \
    ros-humble-ros2-controllers \
    ros-humble-ros2-socketcan \
    ros-humble-rqt-common-plugins \
    ros-humble-rqt-image-overlay \
    ros-humble-rtcm-msgs \
    ros-humble-teleop-twist-joy \
    ros-humble-teleop-twist-keyboard \
    ros-humble-twist-stamper \
    ros-humble-zed-msgs \
    ros-humble-laser-filters \
    ros-humble-micro-ros-msgs \
    ros-humble-husarion-components-description \
    ros-humble-dynamixel-sdk \
    ros-humble-dynamixel-interfaces \
    ros-humble-ros-gz \
    gz-fortress \
    libgz-fortress-dev \
    ros-humble-ros-gz-sim \
    ros-humble-ros-gz-bridge \

# add symlink required to use the streaming features on Jetson inside a container, based on
# https://github.com/stereolabs/zed-docker/blob/fd514606174d8bb09f21a229f1099205b284ecb6/4.X/l4t/devel/Dockerfile#L27C5-L27C95
RUN if [ "$(uname -m)" != "x86_64" ]; \
    then ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0 /usr/lib/aarch64-linux-gnu/libv4l2.so; \
    fi

# fix issues with ament_find_gmock by reinstalling the ros2 gmock and gtest packages
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install --reinstall --no-install-recommends -y \
    ros-humble-gmock-vendor \
    ros-humble-gtest-vendor

# copy entrypoint scripts
RUN mkdir -p /usr/local/bin/scripts/entrypoint_additions
COPY scripts/entrypoint_additions/*.sh /usr/local/bin/scripts/entrypoint_additions/
RUN chmod +x /usr/local/bin/scripts/entrypoint_additions/*.sh || true
COPY cyclonedds.xml /