ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get clean
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null

RUN apt-get update

# fix issues with ament_find_gmock
RUN rm -f /usr/src/gmock
RUN apt-get update && apt-get install -y \
    ros-humble-gmock-vendor \
    ros-humble-gtest-vendor \
    && rm -rf /var/lib/apt/lists/*

# install missing ros2 packages
RUN apt-get update && apt-get install -y \
    ros-humble-can-msgs \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-gazebo-ros2-control \
    ros-humble-topic-tools \
    ros-humble-ros2-socketcan \
    ros-humble-ros2-control \   
    ros-humble-ros2-controllers \
    ros-humble-robot-localization \
    ros-humble-rqt-common-plugins \
    ros-humble-rqt-image-overlay \
    ros-humble-image-pipeline \
    ros-humble-xacro \
    ros-humble-teleop-twist-keyboard \
    ros-humble-teleop-twist-joy \
    ros-humble-twist-stamper \
    ros-humble-magic-enum \
    ros-humble-joint-state-publisher-gui \
    ros-humble-joint-state-publisher \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-foxglove-bridge \
    gdb

RUN pip3 install --no-input --no-cache-dir -U \
    numba==0.58.1 \
    transformations==2022.9.26 \
    icecream==2.1.3

# install gpiod
RUN apt-get update && apt-get install -y \
    libgpiod-dev \
    gpiod \
    && rm -rf /var/lib/apt/lists/*

# install joystick
RUN apt-get update && apt-get install -y \
    joystick \
    evtest \
    && rm -rf /var/lib/apt/lists/*

# install pylon
# RUN if [ "$(uname -m)" = "x86_64" ]; then \
#     wget https://www2.baslerweb.com/media/downloads/software/pylon_software/pylon_7_4_0_14900_linux_x86_64_debs.tar.gz \
#     && mkdir pylon \
#     && tar -xzf pylon_*.tar.gz -C pylon \
#     && apt-get install -y ./pylon/pylon_*.deb ./pylon/codemeter_*.deb \
#     && rm -rf pylon pylon_*.tar.gz; \
#     else \
#     wget https://www2.baslerweb.com/media/downloads/software/pylon_software/pylon_7_4_0_14900_linux_aarch64_debs.tar.gz \
#     && mkdir pylon \
#     && tar -xzf pylon_*.tar.gz -C pylon \
#     && apt-get install -y ./pylon/pylon_*.deb ./pylon/codemeter-lite_*.deb \
#     && rm -rf pylon pylon_*.tar.gz; \
#     fi

# ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/pylon/lib/

# copy entrypoint scripts
RUN mkdir -p /usr/local/bin/scripts
COPY scripts/*entrypoint.sh /usr/local/bin/scripts/
RUN chmod +x /usr/local/bin/scripts/*.sh
